/* This file has been generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2017 Hex-Rays <info@hex-rays.com>

   Detected compiler: Visual C++
*/

#include <windows.h>
#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

INT_PTR __stdcall start(int a1, int a2, int a3, int a4);
int __cdecl read_param(_BYTE *a1);
signed int __cdecl check_password(int a1, int *a2);
unsigned int __cdecl gen_username_TOKEN(_BYTE *a1);
unsigned int __cdecl CHEKC_INPUT(_BYTE *a1, _BYTE *a2);
BOOL sub_401196();
INT_PTR __stdcall DialogFunc(HWND, UINT, WPARAM, LPARAM); // idb
// HMODULE __stdcall GetModuleHandleW(LPCWSTR lpModuleName);
// FARPROC __stdcall GetProcAddress(HMODULE hModule, LPCSTR lpProcName);
// HMODULE __stdcall LoadLibraryA(LPCSTR lpLibFileName);
// void __stdcall __noreturn ExitProcess(UINT uExitCode);
// LRESULT __stdcall SendMessageW(HWND hWnd, UINT Msg, WPARAM wParam, LPARAM lParam);
// BOOL __stdcall SetWindowPos(HWND hWnd, HWND hWndInsertAfter, int X, int Y, int cx, int cy, UINT uFlags);
// INT_PTR __stdcall DialogBoxParamW(HINSTANCE hInstance, LPCWSTR lpTemplateName, HWND hWndParent, DLGPROC lpDialogFunc, LPARAM dwInitParam);
// BOOL __stdcall EndDialog(HWND hDlg, INT_PTR nResult);
// HWND __stdcall GetDlgItem(HWND hDlg, int nIDDlgItem);
// UINT __stdcall GetDlgItemTextA(HWND hDlg, int nIDDlgItem, LPSTR lpString, int cchMax);
// HWND __stdcall SetFocus(HWND hWnd);
// BOOL __stdcall GetWindowRect(HWND hWnd, LPRECT lpRect);
// int __stdcall MessageBoxA(HWND hWnd, LPCSTR lpText, LPCSTR lpCaption, UINT uType);
// DWORD __stdcall SetClassLongW(HWND hWnd, int nIndex, LONG dwNewLong);
// HWND __stdcall GetDesktopWindow();
// HICON __stdcall LoadIconW(HINSTANCE hInstance, LPCWSTR lpIconName);

//-------------------------------------------------------------------------
// Data declarations

_UNKNOWN unk_402050; // weak
char byte_403000[] = { 'a' }; // weak
char byte_403014[44] =
{
  '\x02',
  '\x03',
  '\x06',
  '\n',
  '\x01',
  '\x04',
  '\x0F',
  '\v',
  '\t',
  '\x0E',
  '\x05',
  '\r',
  '\a',
  '\b',
  '\f',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0'
}; // idb
int (__cdecl *dword_403040)(_DWORD, _DWORD) = NULL; // weak
int dword_403044 = 0; // weak
int dword_403048 = 0; // weak
_UNKNOWN unk_403060; // weak
int dword_403128 = 0; // weak
LPCSTR lpText = NULL; // idb
CHAR String[16] =
{
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0'
}; // idb
CHAR byte_403140[52] =
{
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0'
}; // idb
HINSTANCE hInstance = NULL; // idb


//----- (00401000) --------------------------------------------------------
INT_PTR __stdcall start(int a1, int a2, int a3, int a4)
{
  hInstance = GetModuleHandleW(0);
  if ( !sub_401196() )
  {
    MessageBoxA(0, "Can't load functions from DLLs.", "Error!", 0);
    ExitProcess(0);
  }
  return DialogBoxParamW(hInstance, (LPCWSTR)0x81, 0, DialogFunc, 272);
}

//----- (00401051) --------------------------------------------------------
int __cdecl read_param(_BYTE *a1)
{
  int result; // eax

  result = 0;
  if ( *a1 )
  {
    do
      ++result;
    while ( a1[result] );
  }
  return result;
}

//----- (00401066) --------------------------------------------------------
signed int __cdecl check_password(char *PASSWD, int *TOKEN){
  unsigned int v2; // edx
  unsigned int v3; // eax

  *TOKEN = 0;
  pass_idx = 0;
  while ( 1 ){
    index = 0;
    do{
      if ( byte_403000[index] == PASSWD[pass_idx] )
        break;
      ++index;
    }
    while ( index < 0x10 );
    if ( index == 16 ){
      break;
    }
    ++pass_idx;
    *TOKEN = (16 * *TOKEN | byte_403014[index]) ^ 0xA;
    if ( pass_idx >= 8 ){
      return 1;
    }
  }
  return 0;
}

//----- (004010B5) --------------------------------------------------------
unsigned int __cdecl gen_username_TOKEN(_BYTE *a1)
{
  _BYTE *v1; // edx
  unsigned int id; // eax
  bool i; // zf
  int v4; // eax
  unsigned int v5; // [esp+0h] [ebp-4h]

  v1 = a1;
  id = 0;
  for ( i = *a1 == 0; i; i = *v1 == 0 ){
    v5 = id;
    v4 = __ROL4__(id, 5);
    LOBYTE(v4) = BYTE1(v4);
    BYTE1(v4) = __ROL4__(v5, 5);
    id = (unsigned __int8)*v1++ + (v4 ^ 0xC8FA7B6E);
  }
  return id;
}

//----- (004010E7) --------------------------------------------------------
unsigned int __cdecl CHEKC_INPUT(_BYTE *a1, _BYTE *a2)
{
  unsigned int v2; // esi
  int v3; // edx
  unsigned int result; // eax
  unsigned __int8 v5; // cl
  unsigned int TOKEN; // esi
  int v7; // [esp+8h] [ebp-4h]

  v2 = read_param(a1);
  v3 = read_param(a2);
  result = 0;
  if ( v2 )
  {
    do
    {
      v5 = a1[result];
      if ( (v5 < 0x61u || v5 > 0x7Au) && (v5 < 0x41u || v5 > 0x5Au) )
      {
        lpText = "Invalid name!";
        return 0;
      }
      ++result;
    }
    while ( result < v2 );
    dword_403048 = 0;
    if ( v3 != 8 )
    {
      lpText = "Wrong Password!";
      return 0;
    }
    TOKEN = gen_username_TOKEN(a1);
    dword_403128 = v6;
    if ( check_password((int)a2, &v7) && v7 == TOKEN )
      result = dword_403048++ + 1;
    else
      result = dword_403048;
  }
  else
  {
    lpText = "You must type a name!";
  }
  return result;
}
// 403048: using guessed type int dword_403048;
// 403128: using guessed type int dword_403128;

//----- (00401196) --------------------------------------------------------
BOOL sub_401196()
{
  HMODULE v0; // eax
  HMODULE v1; // esi

  v0 = LoadLibraryA("msvcrt.dll");
  v1 = v0;
  if ( !v0 )
    return 0;
  dword_403040 = (int (__cdecl *)(_DWORD, _DWORD))GetProcAddress(v0, "sprintf");
  if ( !dword_403040 )
    return 0;
  dword_403044 = (int)GetProcAddress(v1, "memcmp");
  return dword_403044 != 0;
}
// 403040: using guessed type int (__cdecl *dword_403040)(_DWORD, _DWORD);
// 403044: using guessed type int dword_403044;

//----- (004011DD) --------------------------------------------------------
INT_PTR __stdcall DialogFunc(HWND hDlg, UINT a2, WPARAM a3, LPARAM a4)
{
  HMODULE v5; // eax
  HICON v6; // eax
  HWND v7; // eax
  HWND v8; // eax
  HWND v9; // eax
  HWND v10; // eax
  struct tagRECT Rect; // [esp+0h] [ebp-10h]

  if ( a2 == 16 )
  {
    EndDialog(hDlg, 0);
    ExitProcess(0);
  }
  if ( a2 == 272 )
  {
    v5 = GetModuleHandleW(0);
    v6 = LoadIconW(v5, (LPCWSTR)0x6C);
    SetClassLongW(hDlg, -14, (LONG)v6);
    v7 = GetDesktopWindow();
    GetWindowRect(v7, &Rect);
    SetWindowPos(hDlg, 0, Rect.right / 2 - 200, Rect.bottom / 2 - 100, 0, 0, 5u);
    v8 = GetDlgItem(hDlg, 1001);
    SetFocus(v8);
    v9 = GetDlgItem(hDlg, 1001);
    SendMessageW(v9, 0xC5u, 0xAu, 0);
    v10 = GetDlgItem(hDlg, 1002);
    SendMessageW(v10, 0xC5u, 0x32u, 0);
    return 0;
  }
  if ( a2 != 273 || (unsigned __int16)a3 != 1 )
    return 0;
  GetDlgItemTextA(hDlg, 1001, String, 11);
  GetDlgItemTextA(hDlg, 1002, byte_403140, 51);
  if ( CHEKC_INPUT(String, byte_403140) )
  {
    dword_403040(&unk_403060, "Login Success!\nAccess granted!");
    MessageBoxA(hDlg, (LPCSTR)&unk_403060, (LPCSTR)&unk_402050, 0);
  }
  else
  {
    MessageBoxA(hDlg, lpText, "Login Failure", 0);
  }
  return 1;
}
// 403040: invalid function type has been ignored
// 403040: using guessed type int (__cdecl *dword_403040)(_DWORD, _DWORD);

// ALL OK, 7 function(s) have been successfully decompiled
